[package]
name = "cgfs"
version = "0.1.0"
authors = ["matthew <matthew-ch@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"